// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v1_createProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_createProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202306030115255_v1_createProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
